first commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -123,9 +123,19 @@ jobs:
 
       - name: Deploy to EKS
         run: |
-          if kubectl get deployment $APP_NAME -n $K8S_NAMESPACE; then
-            kubectl set image deployment/$APP_NAME -n $K8S_NAMESPACE $CONTAINER_NAME=$IMAGE_URI
-            kubectl rollout status deployment/$APP_NAME -n $K8S_NAMESPACE
+          if kubectl get deployment $APP_NAME -n $K8S_NAMESPACE > /dev/null 2>&1; then
+          echo "✅ Deployment $APP_NAME exists. Updating image..."
+  
+          CONTAINER_NAME=$(kubectl get deployment $APP_NAME -n $K8S_NAMESPACE -o jsonpath="{.spec.template.spec.containers[0].name}")
+  
+          if [ -n "$CONTAINER_NAME" ]; then
+           kubectl set image deployment/$APP_NAME -n $K8S_NAMESPACE $CONTAINER_NAME=$IMAGE_URI
+          kubectl rollout status deployment/$APP_NAME -n $K8S_NAMESPACE
+           else
+            echo "❌ Error: Could not determine container name."
+          exit 1
+             fi
           else
-            kubectl apply -f k8s/deployment.yaml
+          echo "🚀 Deployment $APP_NAME does not exist. Applying manifest..."
+          kubectl apply -f k8s/deployment.yaml
           fi
